### ISSUE TITLE
can't set up this one on my mac

### ISSUE THREAD

**Issue by mnismayilli** [monikajaskolka/TeXShop-Themes#1]
I unzipped the folder and run the script. Terminal shows everything is changed and done, but when I close and open the Texshop file, the theme is unchanged. I tried to run it many times but it still does not work. Any help would be greatly appreciated.

**Comment by monikajaskolka** [comment]
What version of TeXShop are you using?

**Comment by mnismayilli** [comment]
> What version of TeXShop are you using?
Version 4.44

**Comment by monikajaskolka** [comment]
The shell (.sh) scripts were created to support themes on  TeXShop Version 4.07 and earlier, because at that time the only way of customizing the appearance of TeXShop was via the command line. As of 4.08+, the [TeXShop documentation](https://pages.uoregon.edu/koch/texshop/changes_3.html) states:

> Some people on the internet developed color themes for TeXShop and made them available as shell scripts which reset various TeXShop color setting preferences. These shell scripts still work, but they no longer affect the appearance of TeXShop. After running such a script, you can use "New Theme from Prefs" to convert the "preference color scheme" to a regular Theme.

I have converted the themes into the new .plist format that TeXShop uses, and included instructions in the README for Version 4.08+. Please follow these instructions, and let me know if it works.

**Comment by mnismayilli** [comment]
Thank you very much! It works indeed. Perfect!
